local M = {}
vim.lsp.protocol.CompletionItemKind = {
	Text = " [text]",
	Method = " [method]",
	Function = " [function]",
	Constructor = " [constructor]",
	Field = "ﰠ [field]",
	Variable = " [variable]",
	Class = " [class]",
	Interface = " [interface]",
	Module = " [module]",
	Property = " [property]",
	Unit = " [unit]",
	Value = " [value]",
	Enum = " [enum]",
	Keyword = " [key]",
	Snippet = "﬌ [snippet]",
	Color = " [color]",
	File = " [file]",
	Reference = " [reference]",
	Folder = " [folder]",
	EnumMember = " [enum member]",
	Constant = " [constant]",
	Struct = " [struct]",
	Event = "⌘ [event]",
	Operator = " [operator]",
	TypeParameter = " [type]",
}

M.symbol_kind_icons = {
	Function = "",
	Method = "",
	Variable = "",
	Constant = "",
	Interface = "練",
	Field = "ﰠ",
	Property = "",
	Struct = "",
	Enum = "",
	Class = "",
	File = "",
	Module = "",
	Namespace = "",
	Package = "",
	Constructor = "",
	String = "",
	Number = "",
	Boolean = "◩",
	Array = "",
	Object = "",
	Key = "",
	Null = "ﳠ",
	EnumMember = "",
	Event = "",
	Operator = "",
	TypeParameter = "",
}

M.symbol_kind_colors = {
	Function = "green",
	Method = "green",
	Variable = "blue",
	Constant = "red",
	Interface = "cyan",
	Field = "blue",
	Property = "blue",
	Struct = "cyan",
	Enum = "yellow",
	Class = "magenta",
}

return M
