CompileFlags:
  Add: [
    -m32,
    -isystem/mnt/c/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt,
    -isystem/mnt/c/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/um,
    -isystem/mnt/c/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/shared,
    -isystem/mnt/c/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/winrt,
    -isystem/mnt/c/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/cppwinrt
  ]
Index:
  Background: Skip
